version: '3'
services:
  postgresql:
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=todotom
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
    
#volumes:
#  postgres-data:
#    external: true

