version: '3'
services:
  postgresql:
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=todotom
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgresql/postgres-data:/var/lib/postgresql/data
      - ./postgresql/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"
  ubuntu-zookeeper:
    build: ./kafka-cluster/zookeeper/
    restart: always
    ports:
      - 2081:2081
  ubuntu-kafka:
    build: ./kafka-cluster/kafka/
    restart: always
    depends_on:
      - ubuntu-zookeeper
    links:
      - ubuntu-zookeeper:ubuntu-zookeeper
    ports:
      - 9092:9092
  authentication:
    build: ./authentication
    restart: always
    depends_on:
      - ubuntu-kafka
    links:
      - ubuntu-kafka:ubuntu-kafka
    ports:
      - 5000:5000
  test:
    build: ./kafka-cluster/test
    restart: always
    depends_on:
      - ubuntu-kafka
    links:
      - ubuntu-kafka:ubuntu-kafka
    
#volumes:
#  postgres-data:
#    external: true

