FROM alpine:3.14.0

ARG PASSWD

ARG PREINSTALLED=1

RUN adduser -g "kafka" -HD kafka && \
    echo "kafka:${PASSWD}" | chpasswd -m

ENV HOME=/home/kafka

ENV KAFKA_URL=https://apache.mediamirrors.org/kafka/2.8.0/kafka_2.13-2.8.0.tgz
ENV KAFKA_DIR=kafka_2.13-2.8.0

WORKDIR ${HOME}


RUN if [[ ${PREINSTALLED} = 0 ]] ; then \
    apk add --no-cache wget && \
    wget ${KAFKA_URL} && \
    tar -xzf ${KAFKA_DIR}.tgz && \
    rm ${KAFKA_DIR}.tgz && \
    mv ${KAFKA_DIR} kafka && \
    chown -R kafka:kafka . && \
    chmod -R u+rwx . ; fi
# RUN if [[ ${PREINSTALLED} = 0 ]] ; then \
#     touch caca && \
#     touch pis ; fi

USER kafka

# RUN 
