# FROM python:3.8.10-alpine3.13
# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
# FROM alpine:3.14.0
FROM continuumio/miniconda3
# RUN apt-get install conda && \
#     conda install -r requirements.txt
# RUN apk add --update --no-cache python3 && \
#     python3 -m ensurepip && \
#     pip3 install --no-cache --upgrade pip setuptools



WORKDIR /app

#This extra stage avoids running again the next stage every change in source code
ADD requirements.txt /app

RUN conda config --add channels conda-forge && \
    conda update -n base -c defaults conda && \
    conda install --file requirements.txt

COPY . /app

    # conda create --name authentication --file requirements.txt

# CMD ["source", "activate", "authentication"]

# RUN conda config --add channels conda-forge && \
#     conda update -n base -c defaults conda

# RUN conda update conda && \
# RUN conda config --add channels conda-forge && \
#     conda install --file requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]


# RUN apt-get update \
#     && apt-get -yy install libmariadb-dev

# RUN mkdir -p /usr/src/app
# WORKDIR /usr/src/app

# COPY requirements.txt /usr/src/app
# RUN pip install -r requirements.txt

# ENTRYPOINT [ "flask" ]
# CMD ["run", "--host=0.0.0.0", "--port=5000"]